name: Convert

on: push

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: fabasoad/data-format-converter-action@main
        id: yaml2json
        with:
          input: "regions/worldguard/regions.yml"
          from: "yaml"
          to: "json"
      - name: Print result
        run: echo "${{ steps.yaml2json.outputs.output }}"
